apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: maven-run-
spec:
  pipelineRef:
    name: maven-build
  params:
    - name: repo-url
      value: https://github.com/spring-projects/spring-petclinic
    - name: revision
      value: main
    - name: goals
      value:
      - clean
      - install
  workspaces:
    - name: source-code
      persistentVolumeClaim:
        claimName: maven-pvc
    - name: maven-settings
      emptyDir: {}